### ISSUE TITLE
Formatting problem in <SQL parameter declaration>

### ISSUE THREAD

**Issue by xpe** [JakeWheat/sql-overview#7]
First, thanks for this resource! I heard about it from the [sqlparser-rs] project.

[sqlparser-rs]: https://github.com/sqlparser-rs/sqlparser-rs

In the [SQL 2016 Foundation Grammar, line 6125][1], it looks like `14` got lodged in there before the `<SQL parameter declaration> ::=`. I include several lines before and after to give some comparison.

```txt
<SQL parameter declaration list> ::=
  <left paren> [ <SQL parameter declaration>
      [ { <comma> <SQL parameter declaration> }... ] ] <right paren>

14 <SQL parameter declaration> ::=
  [ <parameter mode> ]
      [ <SQL parameter name> ]
      <parameter type> [ RESULT ]
      [ DEFAULT <parameter default> ]

<parameter default> ::=
    <value expression>
  | <contextually typed value specification>
  | <descriptor value constructor>
```

[1]: https://github.com/JakeWheat/sql-overview/blob/ba79ae408b86150272f058729f695586afd0b31c/sql-2016-foundation-grammar.txt#L6125

This screenshot shows how it renders (badly), both in the left pane (too big) and the navigation sidebar on the right (interrupts the normal ordering):

<img width="1123" alt="formatting-problem-SQL-parameter-definition" src="https://user-images.githubusercontent.com/4576329/133012779-cdccf2fa-79ea-42e2-8290-971bc0de8db5.png">

**Comment by JakeWheat** [comment]
Thanks for the report, I will try to find some time to tweak the code to fix this issue

**Comment by JakeWheat** [comment]
I found two occurrences and removed them manually, not sure where they came from.
